# Generated by Django 5.2.8 on 2026-01-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customuser_picture_studyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='stamp_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='stamp_shape',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
