# Generated by Django 5.2.8 on 2026-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_studyrecord_stamp_color_studyrecord_stamp_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyrecord',
            name='memo',
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='archieved',
            field=models.BooleanField(default=True),
        ),
    ]
