# Generated by Django 5.2.8 on 2026-01-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_studyrecord_memo_studyrecord_archieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyrecord',
            old_name='archieved',
            new_name='achieved',
        ),
    ]
