# Generated by Django 5.2.8 on 2026-01-30 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customuser_managers_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=50)),
                ('study_hour', models.IntegerField(default=0)),
                ('study_minute', models.IntegerField(default=0)),
                ('page_start', models.IntegerField(blank=True, null=True)),
                ('page_end', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
