# Generated by Django 5.2.11 on 2026-02-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_studyrecord_goal_alter_studyrecord_result"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studyrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("goal__isnull", False)),
                fields=("user", "goal"),
                name="uniq_record_per_goal_per_user",
            ),
        ),
    ]
