# Generated by Django 5.1.3 on 2026-04-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_studyrecord_uniq_record_per_goal_per_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "date",
                    "subject",
                    "study_hour",
                    "study_minute",
                    "page_start",
                    "page_end",
                ),
                name="unique_goal_per_user_day_content",
            ),
        ),
    ]
